import React from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { CheckCircle, AlertCircle } from 'lucide-react';

interface ResultsDisplayProps {
  result: string; // The result field from the backend (e.g., "AI-generated" or "Human-created")
}

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ result }) => {
  const isAI = result === 'AI-generated';

  return (
    <div
      className={`space-y-6 shadow-lg rounded-xl p-6 text-gray-800 animate-fade-in transform transition-transform duration-500 ${
        isAI ? 'bg-red-100 scale-105' : 'bg-blue-100 scale-105'
      }`}
    >
      {/* Header with Badge */}
      <div className="flex items-center gap-4 mb-5">
        {isAI ? (
          <Badge className="bg-red-500 text-white px-3 py-1 rounded-full text-sm shadow-sm">
            AI Generated
          </Badge>
        ) : (
          <Badge className="bg-blue-500 text-white px-3 py-1 rounded-full text-sm shadow-sm">
            Human Created
          </Badge>
        )}

        <h3 className="text-lg font-semibold flex items-center gap-2">
          {isAI ? (
            <span className="flex items-center gap-2">
              <AlertCircle className="h-5 w-5 text-red-500" />
              AI Content Detected
            </span>
          ) : (
            <span className="flex items-center gap-2">
              <CheckCircle className="h-5 w-5 text-blue-500" />
              Likely Human Created
            </span>
          )}
        </h3>
      </div>

      {/* Verdict */}
      <p className="text-base leading-relaxed">
        {isAI
          ? 'This image is likely generated by AI. Please verify the source for accuracy.'
          : 'This image is likely created by a human. Authenticity is suggested.'}
      </p>

      {/* Footer Note */}
      <div className="text-sm text-gray-600 mt-6 pt-4 border-t border-gray-200">
        <p>
          <strong>Note:</strong> This analysis is for demonstration purposes only and not a definitive determination.
        </p>
      </div>
    </div>
  );
};

const App: React.FC = () => {
  const [result, setResult] = React.useState<string | null>(null);

  const analyzeImage = () => {
    // Logic to analyze the image and set the result
    setResult('AI-generated'); // Example result
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 p-6">
      {result ? (
        <ResultsDisplay result={result} />
      ) : (
        <Button
          onClick={analyzeImage}
          className="px-6 py-3 bg-blue-600 text-white rounded-lg shadow-md hover:bg-blue-700 transition"
        >
          Analyze Image
        </Button>
      )}
    </div>
  );
};

export default App;
